services:
  ctfserver:
    build: 
      context: .
      args:
        USER_ID: "${UID:-1000}"
        GROUP_ID: "${GID:-1000}"
    ports:
      - "80:80"
    volumes:
      - /opt/tools:/opt/tools:rw
      - /opt/loot:/opt/loot:rw
    environment:
      - CTF_HOST=0.0.0.0
      - CTF_PORT=80
      - CTF_ROOT_DIR=/opt/tools
      - CTF_UPLOAD_DIR=/opt/loot
      - CTF_LOG_LEVEL=info
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
